### ISSUE TITLE
login with device failed

### ISSUE THREAD

**Issue by CityOx** [dani-garcia/vaultwarden#4013]
When I click on the latest version of the iPhone app to authorize a login request from the edge plugin, it says "we were unable to process your request. Please try again or contact us."
I'm using docker deployment, nginx for wildcard domain degeneration. When I tried this, my edge browser and iPhone were on the same LAN, but they both used https to communicate with docker via a degenerated domain name

**Comment by BlackDex** [comment]
This is fixed in the testing tagged images already and have been reported multiple times before.
Either use `testing` tagged images, or wait for a new stable and not use this feature for now.

**Comment by CityOx** [comment]
Got it, thank you

**Comment by CityOx** [comment]
> This is fixed in the testing tagged images already and have been reported multiple times before. Either use `testing` tagged images, or wait for a new stable and not use this feature for now.

I've used the testing tagged image for testing. 
I reinstalled the app and browser plug-in on my iPhone and logged back in with my master password. 

Now there is no longer an error on the app, but after clicking agree, the browser plug-in does not respond, and it still does not log in successfully

**Comment by BlackDex** [comment]
Check if you configured the websockets correctly using the new way

**Comment by CityOx** [comment]
> Check if you configured the websockets correctly using the new way

I'm not sure if there are any wrong settings, please advise if convenient. Thank you.
![a](https://github.com/dani-garcia/vaultwarden/assets/81021167/2f7a2dc5-84c2-4d2e-8f52-54749fdbfe90)

**Comment by BlackDex** [comment]
The connection header is set empty there, that is probably your issue.

**Comment by CityOx** [comment]
> The connection header is set empty there, that is probably your issue.

I looked at and referenced the following links, and I noticed that the example set the connection header to "". I may have misinterpreted this, but if it's convenient, please indicate the correct settings.
https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples

**Comment by BlackDex** [comment]
Wel i think that with npm you shouldn't even add those. It will be handled by setting that websocket option on.

Else, if you checked the example correctly it states the following.

```nginx
# Needed to support websocket connections
# See: https://nginx.org/en/docs/http/websocket.html
# Instead of "close" as stated in the above link we send an empty value.
# Else all keepalive connections will not work.
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      "";
}
# ...
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
```

Which basically says, if the upgrade header is set, set the connection_upgrade variable to `upgrade`, else keep it empty.
In your case it's always empty, which doesn't trigger a correct websocket connection.

But i think you just need to remove both those lines from your config, and NPM will handle it for you i think. But not sure, never used it my self.

**Comment by CityOx** [comment]
> Wel i think that with npm you shouldn't even add those. It will be handled by setting that websocket option on.
> 
> Else, if you checked the example correctly it states the following.
> 
> ```nginx
> # Needed to support websocket connections
> # See: https://nginx.org/en/docs/http/websocket.html
> # Instead of "close" as stated in the above link we send an empty value.
> # Else all keepalive connections will not work.
> map $http_upgrade $connection_upgrade {
>     default upgrade;
>     ''      "";
> }
> # ...
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection $connection_upgrade;
> ```
> 
> Which basically says, if the upgrade header is set, set the connection_upgrade variable to `upgrade`, else keep it empty. In your case it's always empty, which doesn't trigger a correct websocket connection.
> 
> But i think you just need to remove both those lines from your config, and NPM will handle it for you i think. But not sure, never used it my self.

I tried to delete the two lines of configuration, but the problem remained. The app clicked yes, but the plug-in didn't respond. 
I'm confused, and if there's anything I can try, I'd be happy to get your advice, thank you.

**Comment by CityOx** [comment]
I know the correct setup:
When you use npm, you only need to turn on the WS switch and leave it blank in the custom configuration .
